apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: datalove
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: datalove
            image: insertdatadog
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure