apiVersion: apps/v1
kind: Deployment
metadata:
  name: datalove
  namespace: default
spec:
  selector:
    matchLabels:
      app: datalove
  replicas: 1
  template:
    metadata:
      labels:
        app: datalove
    spec:
      containers:
        - name: datalove
          image: insertdatadog
          resources:
            requests:
              memory: '16Mi'
              cpu: '50m'
            limits:
              memory: '32Mi'
              cpu: '60m'
          imagePullPolicy: IfNotPresent