apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{imagen_app_name}#
  namespace: #{namespace}#
  labels:
    tags.datadoghq.com/env: #{env_short_code}#
    tags.datadoghq.com/service: #{imagen_app_name}#
    tags.datadoghq.com/version: #{imagen_version}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "#{imagen_app_name}#"
  template:
    metadata:
      creationTimestamp: 
      labels:
        app: "#{imagen_app_name}#"
        tags.datadoghq.com/env: #{env_short_code}#
        tags.datadoghq.com/service: #{imagen_app_name}#
        tags.datadoghq.com/version: #{imagen_version}#
      annotations:
        ad.datadoghq.com/#{imagen_app_name}#.logs: |-
          [{
            "source": "java",
            "service": "#{imagen_app_name}#",
            "log_processing_rules": [{
              "type": "multi_line",
              "name": "log_start_with_date",
              "pattern" : "\\d{4}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])\\s(0[0-9]|[1][0-9]|2[0-3]):(0[0-9]|[1-5][0-9]):(0[0-9]|[1-5][0-9]).\\d{3}Z?\\s"
            #{dd_logging_info}#
          }]
        ad.datadoghq.com/tags: >-
          {"abinbev_product": "#{imagen_product_name}#","abinbev_tower": "sales_process"}
    spec:
      volumes:
      - name: abi-objetivos-api-persistent-storage
        persistentVolumeClaim:
          claimName: pdo-#{env_short_code}#-pv-claim
      serviceAccountName: #{serviceAccountName}#
      containers:
      - name: #{imagen_app_name}#
        image: #{acr}#/#{imagen}#:#{imagen_version}#
        imagePullPolicy: Always
        volumeMounts:
        - name: abi-objetivos-api-persistent-storage
          mountPath: #{pvc.path}#          
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
#          limits:
#            cpu: 500m
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 3
          timeoutSeconds: 1
        env:
          - name: "spring.cloud.kubernetes.config.namespace"
            value: #{namespace}#
#          - name: "APPLICATIONINSIGHTS_CONNECTION_STRING"
#            value: "InstrumentationKey=#{APPLICATIONINSIGHTS_CONNECTION_STRING}#"
#          - name: "APPLICATIONINSIGHTS_ROLE_NAME"
#            value: "#{imagen_app_name}#-#{env_short_code}#"
#          - name: "JAVA_TOOL_OPTIONS"
#            value: "-javaagent:/tmp/applicationinsights-agent-3.0.0-PREVIEW.7.jar"
          - name: JAVA_OPTS
            value: '-Xms512M -Xmx6G'
          - name: DD_ENV
            value: #{env_short_code}#
          - name: DD_SERVICE
            value: #{imagen_app_name}#
          - name: DD_VERSION
            value: #{imagen_version}#        
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_TRACE_ANALYTICS_ENABLED
            value: "true"
          - name: "DD_TAGS"
            value: "abinbev_product:#{abinbev_product}#,abinbev_tower:#{abinbev_tower}#"
      tolerations:
        - key: sku
          operator: Equal
          value: globant
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
      volumes:
        - name: config-volume
          configMap:
            name: #{imagen_app_name}#-configmap